---
- name: Pull Docker Image
  hosts: all
  tasks:
    # - name: Start Docker Service
    #   service:
    #     name: docker
    #     state: started
    - name: pull an image
      docker_image:
        name: architsangal/speminiproject:latest
        source: pull
    - name: Freeing the port
      shell: docker stop $(docker ps --filter publish="2023")
    - name: Running Docker Image Using a Container
      shell: docker run -p 2023:22 -it -d architsangal/speminiproject